spring :
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/community_board?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jack # root -> 회사 jack -> 개인
    password: jack

#  sql:
#    init:
#      mode: always
#        schema-locations: classpath:data.sql